apiVersion: v1
kind: Service

metadata:
  name: solar-staging-service

  labels:
    app: solar-staging
    env: staging

spec:

  type: LoadBalancer
  loadBalancerIP: 40.88.53.95

  selector:
    app: solar-staging

  ports:

  - name: http

    port: 80

    targetPort: 3000