replicaCount: 1

app: solar-dev

image:
  repository: ""
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

mongodb:
  secretName: mongo-secret
